/* Rows are the solution, "#" is a black square. Clues are keyed by the number
   the grid prints, which the board derives from the rows. */
export type Puzzle = {
    rows: string[];
    across: Record<number, string>;
    down: Record<number, string>;
};

const easy: Puzzle = {
    rows: ["#THIS", "TRADE", "EERIE", "MEMOS", "PSST#"],
    across: {
        1: "Not that",
        5: "Swap, like baseball cards",
        6: "Spooky, like an empty hallway",
        7: "Office notes",
        8: '"Hey, over here!"',
    },
    down: {
        1: "Forest makeup",
        2: "Hurts",
        3: '"The ___" (Dostoevsky novel)',
        4: "Spots",
        5: "Short-term office worker",
    },
};

const hard: Puzzle = {
    rows: [
        "STEM#CLASS#COED",
        "NOVA#OUNCE#ONLY",
        "ARES#UNDER#MOLE",
        "GINSENG#NICE###",
        "##TART#YEAH#FRS",
        "###CARLISLE#EAT",
        "BEAR#YOD#SCYLLA",
        "ERRED#ODD#KELLY",
        "GOSSIP#ION#SAYS",
        "ADO#CRESCENT###",
        "TEN#EACH#ICED##",
        "###MYTH#STORIES",
        "TUBE#TORAH#DADE",
        "OGRE#LEAVE#ANNA",
        "WHAT#ESTER#YEAR",
    ],
    across: {
        1: "Part of a wineglass",
        5: "Elegance",
        10: "Like many college dorms",
        14: "Star that suddenly flares",
        15: "Snow leopard, by another name",
        16: "Sole",
        17: "Greek god of war",
        18: "Beneath",
        19: "Spy who's burrowed in",
        20: "Root in some energy drinks",
        22: "French Riviera city",
        24: "Sour",
        25: '"Sure, sure"',
        26: "Parish priests: Abbr.",
        29: "Cumbrian city near Hadrian's Wall",
        31: "Dig in",
        32: "Chicago footballer",
        35: "Hebrew letter before kaph",
        36: "Monster opposite Charybdis",
        38: "Slipped up",
        40: "Like 1, 3 and 5",
        42: "Grace of Monaco",
        43: "Water-cooler talk",
        45: "Charged particle",
        47: '"Simon ___"',
        48: '"Much ___ About Nothing"',
        49: "Moon shape",
        52: "Perfect score, often",
        53: "Apiece",
        54: "Like summer coffee, often",
        56: "Legend",
        57: "Floors of a building",
        60: "Television, informally",
        63: "Scroll in an ark",
        65: "Miami-___ County",
        66: "Shrek, for one",
        67: "Take off",
        68: '"Frozen" princess',
        69: '"Come again?"',
        70: "Fragrant compound in fruit",
        71: "365 days",
    },
    down: {
        1: "Hitch",
        2: "Singer Amos",
        3: "Happening",
        4: "Blowout wins, in sports slang",
        5: "Nation",
        6: "Breathing organ",
        7: "Plus",
        8: "Acts are divided into them",
        9: "Saturday matinee cliffhangers",
        10: "Arrive",
        11: "Yoko of art and music",
        12: "Building extension",
        13: "Hair color",
        21: "Historical period",
        23: "Chess threat",
        25: 'Language of "schlep" and "kvetch"',
        26: "Guy",
        27: "Comeback",
        28: "Remains",
        30: "British restroom",
        32: "Biblical verb in genealogies",
        33: "Wear away",
        34: "Crime involving a match",
        37: "Beatles ballad about the past",
        39: "Risky",
        41: "Physician, casually",
        44: "Babble",
        46: "Not one or the other",
        50: "Canyon sounds",
        51: "Sgt., e.g.",
        55: 'Keaton of "Annie Hall"',
        56: "Track event",
        57: "Ctrl+S action",
        58: "Poet ___ St. Vincent Millay",
        59: "Brown quickly",
        60: "Haul",
        61: '"Gross!"',
        62: "Support garment",
        64: "Snitch",
    },
};

export const PUZZLES = { easy, hard };
